// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjjgchirrtprvzxiuzdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qamdjaGlycnRwcnZ6eGl1emRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzk3NjAsImV4cCI6MjA2MTY1NTc2MH0._OypI6S_36IYlWpSm-1N_TDvgPN1C4txpY4Jl1-srfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);